name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++
      
    - name: Create Build Directory
      run: |
        if [ ! -d build ]; then
          mkdir build
        fi
    - name: Build
      run: |
        mkdir -p build  
        cd build
        cmake ../gray-scott-sim  
        cmake --build .
    - name: Test
      run: |
        ./build/GSTests




